---

- name: Build a recent ruby via rbenv
  shell: bash -lc "rbenv install {{ ruby_version }} && rbenv global {{ ruby_version }}"
  args:
    creates: /home/{{ default_user }}/.rbenv/versions/{{ ruby_version }}

- name: Install some key gems too!
  shell: bash -lc "gem install bundler && gem install pry && rbenv rehash"
  args:
    creates: /home/{{ default_user }}/.rbenv/shims/pry
