---

- name: Install Dovecot and related packages
  apt: pkg={{ item }} state=installed
  with_items:
    - dovecot-core
    - dovecot-imapd
    - dovecot-lmtpd
    - dovecot-managesieved
    - dovecot-pgsql

- name: Create vmail group
  group: name=vmail state=present gid=5000

- name: Create vmail user
  user: name=vmail group=vmail uid=5000 shell=/usr/sbin/nologin
    state=present

- name: Ensure mail domain directories are in place
  file: path=/home/vmail/{{ item.name }} owner=vmail group=dovecot mode=770
    state=directory
  with_items: vmail_domains

- name: Ensure mail user directories are in place
  file: path=/home/vmail/{{ item.domain }}/{{ item.account }}
    owner=vmail group=dovecot state=directory
  with_items: vmail_users

- name: Specify protocols in dovecot.conf
  lineinfile: dest=/etc/dovecot/dovecot.conf regexp="^protocols ="
    line="protocols = imap lmtp sieve"

- name: Update various dovecot config files
  copy: src=dovecot_{{ item }} dest=/etc/dovecot/conf.d/{{ item }}
  with_items:
    - 10-mail.conf
    - 10-master.conf
    - auth-sql.conf.ext
  notify: restart dovecot

- name: Change some settings in auth.conf
  replace: dest=/etc/dovecot/conf.d/10-auth.conf
    regexp="{{ item.regexp }}" replace="{{ item.line }}"
  with_items:
    - { regexp: "^#disable_plaintext_auth =.*$", line: "disable_plaintext_auth = yes" }
    - { regexp: "^auth_mechanisms =.*$", line: "auth_mechanisms = plain login" }
    - { regexp: "^!include auth-system.*$", line: "#!include auth-system.conf.ext" }
    - { regexp: "^#!include auth-sql.*$", line: "!include auth-sql.conf.ext" }

- name: Add appropriate settings in ssl.conf
  replace: dest=/etc/dovecot/conf.d/10-ssl.conf
    regexp="{{ item.regexp }}" replace="{{ item.line }}"
  with_items:
    - { regexp: "^#ssl =.*$", line: "ssl = required" }
    - { regexp: "^ssl_cert =.*$ ", line: "ssl_cert = <{{ ssl_cert_path }}" }
    - { regexp: "^ssl_key = .*$", line: "ssl_key = <{{ ssl_key_path }}" }
    - { regexp: "^#ssl_protocols =.*$", line: "ssl_protocols = !SSLv2 !SSLv3" }

- name: Add SQL config for Dovecot
  template: src=dovecot_sql.conf.ext.j2 dest=/etc/dovecot/dovecot-sql.conf.ext
  notify: restart dovecot

- name: Add LDA config for Dovecot
  template: src=dovecot_15-lda.conf.j2 dest=/etc/dovecot/conf.d/15-lda.conf
  notify: restart dovecot

- name: Ensure correct permissions on Dovecot config directory
  file: state=directory path=/etc/dovecot
    group=dovecot owner=vmail mode=770 recurse=yes
  notify: restart dovecot

- name: Set firewall rules for dovecot
  ufw: rule=allow port=imaps proto=tcp
