---

- name: Install dspam and related packages
  apt: pkg={{ item }} state=present
  with_items:
    - dovecot-antispam
    - dovecot-sieve
    - dspam
    - postfix-pcre

- name: Create dspam directory
  file: state=directory path=/home/vmail/dspam group=dspam owner=dspam

- name: Put dspam configuration files in place
  copy: src="{{ item }}" dest=/etc/dspam/{{ item }} owner=dspam group=dspam
  with_items:
    - default.prefs
    - dspam.conf
  notify:
    - restart postfix
    - restart dovecot

- name: Put dspam postfix configuration in place
  copy: src=dovecot_filter_access dest=/etc/postfix/dspam_filter_access
    owner=root group=root
  notify: restart postfix

- name: Put dspam dovecot configuration in place
  copy: src=dovecot_{{ item }} dest=/etc/dovecot/conf.d/{{ item }}
    owner=vmail group=dovecot
  with_items:
    - 20-imap.conf
    - 90-plugin.conf
  notify: restart dovecot
