---

- name: Install OpenDKIM and related packages
  apt: pkg={{ item }} state=present
  with_items:
    - opendkim
    - opendkim-tools

- name: Create OpenDKIM config directory
  file: state=directory path=/etc/opendkim group=opendkim owner=opendkim

- name: Create OpenDKIM key directories
  file: state=directory path=/etc/opendkim/keys/{{ item.name }}
    group=opendkim owner=opendkim
  with_items: vmail_domains

- name: Generate OpenDKIM keys
  command: opendkim-genkey -r -d {{ item.name }}
    -D /etc/opendkim/keys/{{ item.name }}/
    creates=/etc/opendkim/keys/{{ item.name }}/default.private
  with_items: vmail_domains

- name: Put opendkim.conf into place
  copy: src=opendkim.conf dest=/etc/opendkim.conf owner=opendkim group=opendkim

- name: Put additional OpenDKIM configuration files into place
  template: src=opendkim_{{ item }}.j2 dest=/etc/opendkim/{{ item }}
    owner=opendkim group=opendkim
  with_items:
    - KeyTable
    - SigningTable
    - TrustedHosts
  notify:
    - restart opendkim
    - restart postfix

- name: Set OpenDKIM config directory permissions
  file: state=directory path=/etc/opendkim
    group=opendkim owner=opendkim mode=700 recurse=yes
  notify:
    - restart opendkim
    - restart postfix
