---

- name: Install database packages
  apt: pkg={{ item }} state=present
  with_items:
    - postgresql-{{ pg_version }}
    - python-psycopg2

- name: Set postgres password
  postgresql_user: db=postgres name=postgres
  become_user: postgres
