---

- name: Install database packages
  apt: pkg={{ item }} state=present
  with_items:
    - postgresql-{{ pg_version }}
    - python-psycopg2

- name: Set postgres password
  postgresql_user: db=postgres name=postgres password="{{ db_admin_pass }}"
  become_user: postgres

- name: Enable md5 auth for the mail database
  lineinfile: dest=/etc/postgresql/{{ pg_version }}/main/pg_hba.conf
    insertbefore="^local\s+all\s+all\s+peer$"
    line="local  {{ db_mail_database }}  all  md5" state=present
  notify: restart postgres
