---

- name: Update apt cache
  apt: update_cache=yes

- name: Install aptitude
  apt: pkg=aptitude state=present

- name: Upgrade safely
  apt: upgrade=safe
  notify: remove unneeded packages

- name: Enable backports
  apt_repository:
    repo: deb http://mirrors.linode.com/debian stretch-backports main
    state: present
