---

- name: Tighten SSH security
  template: src=sshd.j2 dest=/etc/ssh/sshd_config
  notify: restart ssh

- name: Install security-related packages
  apt: pkg={{ item }} state=present
  with_items:
    - fail2ban
    - lynis
    - rkhunter
    - ufw
    - whois

- name: Add fail2ban configuration
  template: src=fail2ban.j2 dest=/etc/fail2ban/jail.local
  notify: restart fail2ban

- name: Ensure fail2ban is running
  service: name=fail2ban state=started

- name: Deny everything
  ufw: policy=deny

- name: Set firewall rule for DNS
  ufw: rule=allow port=domain

- name: Set firewall rules for SSH
  ufw: rule=allow port=ssh proto=tcp

- name: Enable UFW
  ufw: state=enabled

- name: Check config of ufw
  command: cat /etc/ufw/ufw.conf
  register: ufw_config
  changed_when: False # never report as "changed"
