---

- name: Add default user
  user: name={{ default_user }}
    state=present
    groups=sudo
    shell={{ default_shell }}
    password={{ default_pass }}

- name: Add pubkey to default user authorized_keys
  authorized_key: user={{ default_user }}
    key="{{ lookup('file', ssh_local_pubkey_path) }}"

- name: Create a dir for building source packages
  file: path={{ default_build_dir }} owner={{ default_user }} state=directory
