---

- name: Install lisp packages
  apt: pkg={{ item }} state=latest
  with_items:
    - sbcl
    - sbcl-doc
    - sbcl-source
    - cl-quicklisp

- name: Ensure builds dir
  file: path={{ default_build_dir }} owner={{ default_user }}
    state=directory

- name: Download Clozure CL
  get_url: url=ftp://ftp.clozure.com/pub/release/1.10/ccl-1.10-linuxx86.tar.gz
    dest={{ default_build_dir }}/ccl.tar.gz

- name: Extract Clozure CL
  unarchive: src={{ default_build_dir }}/ccl.tar.gz
    dest={{ default_build_dir }} copy=no
    owner={{ default_user }} group={{ default_user }} mode=755
    creates={{ default_build_dir }}/ccl

- name: Symlink ccl64
  file: src={{ default_build_dir }}/ccl/lx86cl64
    dest=/usr/bin/ccl state=link mode=755
