---

- name: restart mediagoblin
  service: name={{ item }} state=restarted enabled=yes
  with_items:
    - mediagoblin-paster
    - mediagoblin-celery

- name: run migrations
  shell: ./bin/gmg dbupdate
  args:
    chdir: /srv/www/media.{{ domain }}/mediagoblin
  become_user: "{{ mediagoblin_user }}"
