---

- name: Ensure builds directory is present
  file: path={{ default_build_dir }} state=directory
  become_user: "{{ default_user }}"

- name: Checkout a copy of Clozure CL
  subversion: repo=http://svn.clozure.com/publicsvn/openmcl/release/1.10/linuxx86/ccl
    dest={{ default_build_dir}}/ccl force=yes
  become_user: "{{ default_user }}"

- name: Copy the ccl64 script onto the PATH
  command: cp /home/{{ default_user }}/bin/builds/ccl/scripts/ccl64 /usr/local/bin/ccl
  args:
    creates: /usr/local/bin/ccl

- name: Set CCL_DEFAULT_DIRECTORY in the ccl script
  replace: dest=/usr/local/bin/ccl regexp='CCL_DEFAULT_DIRECTORY=/(.*)$'
    replace="/home/{{ default_user }}/bin/builds/ccl"
