---

- name: Install quicklisp
  command: sbcl --load /usr/share/cl-quicklisp/quicklisp.lisp
    --eval "(quicklisp-quickstart:install)"
  args:
    creates: /home/{{ default_user }}/quicklisp

- name: Add init files for ccl and sbcl
  template: src=../../templates/lisp-init.j2
    dest=/home/{{ default_user }}/{{ item }}
  with_items:
    - .ccl-init.lisp
    - .sbclrc
