---

- name: Add default user to sudoers
  user: name={{ default_user }}
        state=present
        groups=sudo
        append=yes

- name: Add pubkey to default user authorized_keys
  authorized_key: user={{ default_user }}
    key="{{ lookup('file', default_user_pub_key) }}"

- name: Add contrib and non-free apt repos
  template: src=sources.list.j2 dest=/etc/apt/sources.list

- name: Get latest package data
  apt: update_cache=yes

- name: Ensure wifi firmware is installed
  apt: pkg=firmware-iwlwifi state=present

- name: Run any safe upgrade
  apt: upgrade=safe

- name: He who lacks version control and build tools is not part of the world
  apt: pkg={{ item }} state=present
  with_items:
    - build-essential
    - git
    - mercurial
    - bzr
    - darcs
    - subversion
    - cvs

- name: Add git config
  template: src=git_config.j2 dest=/home/{{ default_user }}/.gitconfig
    owner={{ default_user }} group={{ default_user }}

- name: Install some handy shell tools
  apt: pkg={{ item }} state=present
  with_items:
    - fonts-inconsolata
    - silversearcher-ag
    - apt-file
    - powertop
    - htop
    - iotop
    - iftop
    - slurm
    - lsof
    - dstat
    - glances
    - nethogs
    - rlwrap
    - cloc
    - tree

- name: Screw session saving
  replace: regexp="(name=\"SaveOnExit\" type=\"string\") value=\"true" replace="\1 value=\"false\""
    dest=/home/{{ default_user }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml

- name: Really screw session saving
  file: path=/home/{{ default_user }}/.cache/sessions state=absent

- name: Caps Lock is an abomination
  lineinfile: name=/home/{{ default_user }}/.xsessionrc
    line="setxkbmap -option 'ctrl:nocaps'" create=yes state=present
  become_user: "{{ default_user }}"

# TODO: Maybe tighten SSHd security here? Allowed users, no root, etc.
