---

# See: http://wiki.znc.in/Running_ZNC_as_a_system_daemon

- name: Install znc
  apt: pkg=znc state=present

- name: Create znc group
  group: name=znc state=present

- name: Create znc user
  user: name=znc group=znc state=present home=/var/lib/znc
    system=yes shell=/usr/sbin/nologin

- name: Add ZNC systemd service
  copy: src=znc.service dest=/etc/systemd/system/znc.service

- name: Create a combined version of the private key with public cert and intermediate + root CAs
  shell: cat {{ ssl_key_path }} {{ ssl_cert_path }} > /var/lib/znc/znc.pem
    creates=/var/lib/znc/znc.pem

- name: Ensure znc user and group can read cert
  file: path=/var/lib/znc/znc.pem group=znc owner=znc mode=640

- name: Create znc config directory
  file: path=/var/lib/znc/configs state=directory group=znc owner=znc

- name: Check for existing config file
  command: cat /var/lib/znc/configs/znc.conf
  register: znc_config
  ignore_errors: True
  changed_when: False  # never report as "changed"

- name: Copy znc configuration file into place
  template: src=znc.conf.j2 dest=/var/lib/znc/configs/znc.conf
   owner=znc group=znc
  when: znc_config.rc != 0
  notify: restart znc

- name: Set firewall rule for znc
  ufw: rule=allow port=6697 proto=tcp
