---

- name: Make mediagoblin working directory
  file: path=/srv/www/media.{{ domain }} owner=mediagoblin group=www-data
    state=directory

- name: Checkout mediagoblin
  git: repo=git://git.savannah.gnu.org/mediagoblin.git accept_hostkey=true
    dest=/srv/www/media.{{ domain }}/mediagoblin version=stable recursive=yes
  become_user: "{{ mediagoblin_user }}"

- name: Add directory for uploaded media
  file: path=/srv/www/media.{{ domain }}/mediagoblin/user_dev
    state=directory owner=mediagoblin group=www-data

- name: Build mediagoblin
  shell: ./bootstrap.sh && ./configure && make
  args:
    chdir: /srv/www/media.{{ domain }}/mediagoblin
    creates: /srv/www/media.{{ domain }}/mediagoblin/bin/gmg
  become_user: "{{ mediagoblin_user }}"

- name: Install flup
  shell: ./bin/easy_install flup
  args:
    chdir: /srv/www/media.{{ domain }}/mediagoblin
  become_user: "{{ mediagoblin_user }}"
  changed_when: false # never report as changed

- name: Install scikits for Audio plugin
  shell: ./bin/pip install scikits.audiolab
  args:
    chdir: /srv/www/media.{{ domain }}/mediagoblin
  become_user: "{{ mediagoblin_user }}"
  changed_when: false
