---

- hosts: metaobject
  remote_user: deploy
  sudo: yes
  vars_files:
    - vars/metaobject.yml
  roles:
    - { role: thinkpad, tags: ['thinkpad'] }
    - { role: developer, tags: ['developer'] }
